apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.superuser.secretName }}
  labels:
    app: {{ .Release.Name }}
    component: database
    type: superuser
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  username: {{ .Values.cnpg.superuser.credentials.username }}
  password: {{ .Values.cnpg.superuser.credentials.password }}
