apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-migrations"
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
data:
  V1__initial_schema.sql: |-
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      completed BOOLEAN DEFAULT FALSE
    );
  V2__add_completion_date.sql: |-
    ALTER TABLE todos 
    ADD COLUMN IF NOT EXISTS completion_date TIMESTAMP;
