image:
  repository: todo-app
  tag: 1.0.4
  pullPolicy: IfNotPresent

backend:
  name: todo-backend
  port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

frontend:
  name: todo-frontend
  port: 80
  image:
    repository: todo-frontend
    tag: 1.0.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

cnpg:
  enabled: true
  clusterName: todo-db
  instances: 1
  storage:
    size: 1Gi
    storageClass: local-path
  database:
    name: todos
    owner: todoapp
  superuser:
    secretName: todo-db-superuser

ingress:
  enabled: true
  host: todo.local
