backend:
  name: todo-backend
  image:
    repository: alanjumeaucourtHUB/todo-app
    tag: 1.0.5
    pullPolicy: IfNotPresent
  port: 8000
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

frontend:
  name: todo-frontend
  image:
    repository: alanjumeaucourtHUB/todo-frontend
    tag: 1.0.5
    pullPolicy: IfNotPresent
  port: 80
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

cnpg:
  enabled: true
  clusterName: todo-db
  instances: 1
  storage:
    size: 1Gi
    storageClass: local-path
  database:
    name: todos
    owner: todoapp
  superuser:
    secretName: todo-db-superuser

ingress:
  enabled: true
  host: todo.local

migrations:
  enabled: true
  version: "1.0.5"
